### PR TITLE
Merge current master and develop branches

### PR DESCRIPTION
**Pull request by tsjensen**
Hi, since you mentioned in #468 that it is currently an obstacle for you to get the develop and master branches merged ... maybe this helps.

I merged them both into master on my fork. The merged master branch is 6 commits ahead of your devlop branch, containing all meaningful changes by contributors. The other change from greenkeeper etc.  are in the top commit (by me, now). Hope this makes sense when you look at it.

So, you can (if you dare 😉) just force pull my master and you should be done.

Hope this helps!

Clipboard01

### CODE REVIEW

**Comment by thkl** [comment]
oh wow this is crazy ;) i will take a look into it .. thanks a lot

**Comment by tsjensen** [comment]
I made two additional commits, as you see above. But now it should be ready for you 😃

**Comment by thkl** [comment]
there are some conflicts left to fix but this should be manageable ...

**Comment by tsjensen** [comment]
@thkl Yeah, it looks a mess in GitHub, which is why I made the screenshot.

In order to understand the changes, look at the commits added to *your* devlop branch on *my* master (they are just a handful of commits). Then check if they correctly represent the contents of the original master (I think they do).

**Comment by tsjensen** [comment]
The conflicts are normal after merging. Just force pull, don't try to fix conflicts. They are already fixed on my master.

**Comment by Soilman82** [comment]
This would be very nice if you do this. :-) I would also appreciate a new npm Version :-)

**Pull request merged**
